name: Machine Learning Workflow CI

# Jalankan otomatisasi ini setiap kali ada file baru yang di-push ke branch main
on:
  push:
    branches: [ main ]

jobs:
  re-train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        pip install mlflow==2.19.0 scikit-learn pandas

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --no-conda

    # Langkah tambahan untuk poin SKILLED (Menyimpan hasil training ke GitHub)
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-retrained-results
        path: MLProject/mlruns/
